// Code generated by oascmd-gen. DO NOT EDIT.

package petstoregen

import (
	"encoding/json"
	"fmt"
	"net/url"
	"os"
	"strconv"

	"github.com/spf13/cobra"

	"github.com/samishal1998/openapi-commands"
)

// Owner is the "Owner" component schema.
type Owner struct {
	Name string `json:"name"`
	Pets []Pet  `json:"pets,omitempty"`
}

// Pet: A pet in the store.
type Pet struct {
	ID         string          `json:"id"`
	Name       string          `json:"name"`
	Kind       string          `json:"kind,omitempty"`
	Age        int64           `json:"age,omitempty"`
	Vaccinated bool            `json:"vaccinated,omitempty"`
	Nicknames  []string        `json:"nicknames,omitempty"`
	Owner      *Owner          `json:"owner,omitempty"`
	Metadata   json.RawMessage `json:"metadata,omitempty"`
}

// NewCommandTree returns the full generated command tree: group commands
// with every operation command attached. Attach the result onto your root
// command, or use the per-operation constructors directly.
func NewCommandTree(exec oascmd.ExecOptions) []*cobra.Command {
	root := &cobra.Command{}
	groups := map[string]*cobra.Command{"": root}
	group := func(path ...string) *cobra.Command {
		key := ""
		cmd := root
		for _, word := range path {
			key += "/" + word
			child, ok := groups[key]
			if !ok {
				child = &cobra.Command{Use: word}
				cmd.AddCommand(child)
				groups[key] = child
			}
			cmd = child
		}
		return cmd
	}
	group("dns", "records").AddCommand(NewDNSRecordsGetCommand(exec))
	group("internal", "dump").AddCommand(NewInternalDumpDebugCommand(exec))
	group("legacy").AddCommand(NewLegacyPingCommand(exec))
	group("orders").AddCommand(NewOrdersCreateCommand(exec))
	group("pets").AddCommand(NewPetsListCommand(exec))
	group("pets").AddCommand(NewPetsCreateCommand(exec))
	group("pets").AddCommand(NewPetsDeleteCommand(exec))
	group("pets").AddCommand(NewPetsGetCommand(exec))
	group("tools", "renamed").AddCommand(NewToolsRenamedThingCommand(exec))
	group("shipments").AddCommand(NewShipmentsCreateCommand(exec))
	group("untagged", "anon").AddCommand(NewUntaggedAnonPutCommand(exec))
	return root.Commands()
}

// NewDNSRecordsGetCommand returns the "dns records get" command (GET
// /dns/records).
func NewDNSRecordsGetCommand(exec oascmd.ExecOptions) *cobra.Command {
	var (
		flagDomain string
	)
	cmd := &cobra.Command{
		Use:   "get",
		Short: "List DNS records",
	}
	cmd.Flags().StringVar(&flagDomain, "domain", "", "")
	cmd.Flags().Bool("json", false, "print the raw JSON response")
	_ = cmd.MarkFlagRequired("domain")
	cmd.RunE = func(cmd *cobra.Command, args []string) error {
		req := oascmd.Request{
			Method: "GET",
			Path:   "/dns/records",
			Query:  url.Values{},
		}
		req.Query.Set("domain", flagDomain)
		e := exec
		raw, _ := cmd.Flags().GetBool("json")
		e.Raw = e.Raw || raw
		if e.Out == nil {
			e.Out = os.Stdout
		}
		return oascmd.Execute(cmd.Context(), e, req)
	}
	return cmd
}

// NewInternalDumpDebugCommand returns the "internal dump debug" command
// (GET /internal/debug).
func NewInternalDumpDebugCommand(exec oascmd.ExecOptions) *cobra.Command {
	cmd := &cobra.Command{
		Use:    "debug",
		Short:  "Hidden debug dump",
		Hidden: true,
	}
	cmd.Flags().Bool("json", false, "print the raw JSON response")
	cmd.RunE = func(cmd *cobra.Command, args []string) error {
		req := oascmd.Request{
			Method: "GET",
			Path:   "/internal/debug",
		}
		e := exec
		raw, _ := cmd.Flags().GetBool("json")
		e.Raw = e.Raw || raw
		if e.Out == nil {
			e.Out = os.Stdout
		}
		return oascmd.Execute(cmd.Context(), e, req)
	}
	return cmd
}

// NewLegacyPingCommand returns the "legacy ping" command (GET
// /legacy/ping).
func NewLegacyPingCommand(exec oascmd.ExecOptions) *cobra.Command {
	cmd := &cobra.Command{
		Use:        "ping",
		Short:      "Deprecated ping",
		Deprecated: "this operation is deprecated",
	}
	cmd.Flags().Bool("json", false, "print the raw JSON response")
	cmd.RunE = func(cmd *cobra.Command, args []string) error {
		req := oascmd.Request{
			Method: "GET",
			Path:   "/legacy/ping",
		}
		e := exec
		raw, _ := cmd.Flags().GetBool("json")
		e.Raw = e.Raw || raw
		if e.Out == nil {
			e.Out = os.Stdout
		}
		return oascmd.Execute(cmd.Context(), e, req)
	}
	return cmd
}

// NewOrdersCreateCommand returns the "orders create" command (POST
// /orders).
func NewOrdersCreateCommand(exec oascmd.ExecOptions) *cobra.Command {
	var (
		bodyPetID    string
		bodyQuantity int64
		bodyExpress  bool
		flagData     string
	)
	cmd := &cobra.Command{
		Use:   "create",
		Short: "Create an order",
	}
	cmd.Flags().StringVar(&bodyPetID, "pet-id", "", "The pet being ordered")
	cmd.Flags().Int64Var(&bodyQuantity, "quantity", 0, "")
	cmd.Flags().BoolVar(&bodyExpress, "express", false, "")
	cmd.Flags().StringVar(&flagData, "data", "", "request body as raw JSON (wins over per-property flags)")
	cmd.Flags().Bool("json", false, "print the raw JSON response")
	cmd.RunE = func(cmd *cobra.Command, args []string) error {
		req := oascmd.Request{
			Method: "POST",
			Path:   "/orders",
		}
		body := map[string]any{}
		if cmd.Flags().Changed("pet-id") {
			body["petId"] = bodyPetID
		}
		if cmd.Flags().Changed("quantity") {
			body["quantity"] = bodyQuantity
		}
		if cmd.Flags().Changed("express") {
			body["express"] = bodyExpress
		}
		switch {
		case flagData != "":
			req.RawBody = []byte(flagData)
		case len(body) > 0:
			req.Body = oascmd.NestBody([]string{"json"}, body)
		}
		e := exec
		raw, _ := cmd.Flags().GetBool("json")
		e.Raw = e.Raw || raw
		if e.Out == nil {
			e.Out = os.Stdout
		}
		return oascmd.Execute(cmd.Context(), e, req)
	}
	return cmd
}

// NewPetsListCommand returns the "pets list" command (GET /pets).
func NewPetsListCommand(exec oascmd.ExecOptions) *cobra.Command {
	var (
		flagLimit  int64
		flagStatus string
		flagTags   []string
		flagLong   bool
	)
	cmd := &cobra.Command{
		Use:   "list",
		Short: "List pets",
	}
	cmd.Flags().Int64Var(&flagLimit, "limit", 20, "Max results per page")
	cmd.Flags().StringVar(&flagStatus, "status", "", "(one of: available, pending, sold)")
	cmd.Flags().StringSliceVar(&flagTags, "tags", nil, "Filter by tags")
	cmd.Flags().BoolVarP(&flagLong, "long", "l", false, "")
	cmd.Flags().Bool("json", false, "print the raw JSON response")
	cmd.RunE = func(cmd *cobra.Command, args []string) error {
		if cmd.Flags().Changed("status") {
			if err := oascmd.ValidateEnum("status", []string{"available", "pending", "sold"}, flagStatus); err != nil {
				return err
			}
		}
		req := oascmd.Request{
			Method: "GET",
			Path:   "/pets",
			Query:  url.Values{},
		}
		req.Query.Set("limit", strconv.FormatInt(flagLimit, 10))
		if cmd.Flags().Changed("status") {
			req.Query.Set("status", flagStatus)
		}
		if cmd.Flags().Changed("tags") {
			for _, v := range flagTags {
				req.Query.Add("tags", v)
			}
		}
		if cmd.Flags().Changed("long") {
			req.Query.Set("verbose", strconv.FormatBool(flagLong))
		}
		e := exec
		raw, _ := cmd.Flags().GetBool("json")
		e.Raw = e.Raw || raw
		if e.Out == nil {
			e.Out = os.Stdout
		}
		return oascmd.Execute(cmd.Context(), e, req)
	}
	return cmd
}

// NewPetsCreateCommand returns the "pets create" command (POST /pets).
func NewPetsCreateCommand(exec oascmd.ExecOptions) *cobra.Command {
	var (
		bodyName       string
		bodyKind       string
		bodyAge        int64
		bodyWeight     float64
		bodyVaccinated bool
		bodyNicknames  []string
		flagData       string
	)
	cmd := &cobra.Command{
		Use:   "create",
		Short: "Create a pet",
	}
	cmd.Flags().StringVar(&bodyName, "name", "", "The pet's name")
	cmd.Flags().StringVar(&bodyKind, "kind", "", "(one of: dog, cat, bird)")
	cmd.Flags().Int64Var(&bodyAge, "age", 0, "")
	cmd.Flags().Float64Var(&bodyWeight, "weight", 0, "")
	cmd.Flags().BoolVar(&bodyVaccinated, "vaccinated", false, "")
	cmd.Flags().StringSliceVar(&bodyNicknames, "nicknames", nil, "")
	cmd.Flags().StringVar(&flagData, "data", "", "request body as raw JSON (wins over per-property flags)")
	cmd.Flags().Bool("json", false, "print the raw JSON response")
	cmd.RunE = func(cmd *cobra.Command, args []string) error {
		if cmd.Flags().Changed("kind") {
			if err := oascmd.ValidateEnum("kind", []string{"dog", "cat", "bird"}, bodyKind); err != nil {
				return err
			}
		}
		req := oascmd.Request{
			Method: "POST",
			Path:   "/pets",
		}
		body := map[string]any{}
		if cmd.Flags().Changed("name") {
			body["name"] = bodyName
		}
		if cmd.Flags().Changed("kind") {
			body["kind"] = bodyKind
		}
		if cmd.Flags().Changed("age") {
			body["age"] = bodyAge
		}
		if cmd.Flags().Changed("weight") {
			body["weight"] = bodyWeight
		}
		if cmd.Flags().Changed("vaccinated") {
			body["vaccinated"] = bodyVaccinated
		}
		if cmd.Flags().Changed("nicknames") {
			body["nicknames"] = bodyNicknames
		}
		switch {
		case flagData != "":
			req.RawBody = []byte(flagData)
		case len(body) > 0:
			req.Body = body
		}
		e := exec
		raw, _ := cmd.Flags().GetBool("json")
		e.Raw = e.Raw || raw
		if e.Out == nil {
			e.Out = os.Stdout
		}
		return oascmd.Execute(cmd.Context(), e, req)
	}
	return cmd
}

// NewPetsDeleteCommand returns the "pets delete" command (DELETE
// /pets/{petId}).
func NewPetsDeleteCommand(exec oascmd.ExecOptions) *cobra.Command {
	var (
		flagPetID string
	)
	cmd := &cobra.Command{
		Use:   "delete",
		Short: "Delete a pet",
	}
	cmd.Flags().StringVar(&flagPetID, "pet-id", "", "")
	cmd.Flags().Bool("json", false, "print the raw JSON response")
	cmd.Flags().Bool("yes", false, "skip the confirmation prompt")
	_ = cmd.MarkFlagRequired("pet-id")
	cmd.RunE = func(cmd *cobra.Command, args []string) error {
		if yes, _ := cmd.Flags().GetBool("yes"); !yes {
			ok, err := oascmd.Confirm(cmd.InOrStdin(), cmd.ErrOrStderr(), "About to run DELETE /pets/{petId}. Continue?")
			if err != nil {
				return err
			}
			if !ok {
				return fmt.Errorf("aborted")
			}
		}
		req := oascmd.Request{
			Method:     "DELETE",
			Path:       "/pets/{petId}",
			PathParams: map[string]string{},
		}
		req.PathParams["petId"] = flagPetID
		e := exec
		raw, _ := cmd.Flags().GetBool("json")
		e.Raw = e.Raw || raw
		if e.Out == nil {
			e.Out = os.Stdout
		}
		return oascmd.Execute(cmd.Context(), e, req)
	}
	return cmd
}

// NewPetsGetCommand returns the "pets get" command (GET /pets/{petId}).
func NewPetsGetCommand(exec oascmd.ExecOptions) *cobra.Command {
	var (
		flagPetID string
	)
	cmd := &cobra.Command{
		Use:   "get",
		Short: "Get a pet",
	}
	cmd.Flags().StringVar(&flagPetID, "pet-id", "", "")
	cmd.Flags().Bool("json", false, "print the raw JSON response")
	_ = cmd.MarkFlagRequired("pet-id")
	cmd.RunE = func(cmd *cobra.Command, args []string) error {
		req := oascmd.Request{
			Method:     "GET",
			Path:       "/pets/{petId}",
			PathParams: map[string]string{},
		}
		req.PathParams["petId"] = flagPetID
		e := exec
		raw, _ := cmd.Flags().GetBool("json")
		e.Raw = e.Raw || raw
		if e.Out == nil {
			e.Out = os.Stdout
		}
		return oascmd.Execute(cmd.Context(), e, req)
	}
	return cmd
}

// NewToolsRenamedThingCommand returns the "tools renamed thing" command
// (GET /renamed).
func NewToolsRenamedThingCommand(exec oascmd.ExecOptions) *cobra.Command {
	cmd := &cobra.Command{
		Use:   "thing",
		Short: "Renamed via x-cli-name",
	}
	cmd.Flags().Bool("json", false, "print the raw JSON response")
	cmd.RunE = func(cmd *cobra.Command, args []string) error {
		req := oascmd.Request{
			Method: "GET",
			Path:   "/renamed",
		}
		e := exec
		raw, _ := cmd.Flags().GetBool("json")
		e.Raw = e.Raw || raw
		if e.Out == nil {
			e.Out = os.Stdout
		}
		return oascmd.Execute(cmd.Context(), e, req)
	}
	return cmd
}

// NewShipmentsCreateCommand returns the "shipments create" command (POST
// /shipments).
func NewShipmentsCreateCommand(exec oascmd.ExecOptions) *cobra.Command {
	var (
		bodyAddress string
		bodyCarrier string
		flagData    string
	)
	cmd := &cobra.Command{
		Use:   "create",
		Short: "Create a shipment",
	}
	cmd.Flags().StringVar(&bodyAddress, "address", "", "")
	cmd.Flags().StringVar(&bodyCarrier, "carrier", "", "(one of: ups, dhl)")
	cmd.Flags().StringVar(&flagData, "data", "", "request body as raw JSON (wins over per-property flags)")
	cmd.Flags().Bool("json", false, "print the raw JSON response")
	cmd.RunE = func(cmd *cobra.Command, args []string) error {
		if cmd.Flags().Changed("carrier") {
			if err := oascmd.ValidateEnum("carrier", []string{"ups", "dhl"}, bodyCarrier); err != nil {
				return err
			}
		}
		req := oascmd.Request{
			Method: "POST",
			Path:   "/shipments",
		}
		body := map[string]any{}
		if cmd.Flags().Changed("address") {
			body["address"] = bodyAddress
		}
		if cmd.Flags().Changed("carrier") {
			body["carrier"] = bodyCarrier
		}
		switch {
		case flagData != "":
			req.RawBody = []byte(flagData)
		case len(body) > 0:
			req.Body = oascmd.NestBody([]string{"data", "attributes"}, body)
		}
		e := exec
		raw, _ := cmd.Flags().GetBool("json")
		e.Raw = e.Raw || raw
		if e.Out == nil {
			e.Out = os.Stdout
		}
		return oascmd.Execute(cmd.Context(), e, req)
	}
	return cmd
}

// NewUntaggedAnonPutCommand returns the "untagged anon put" command (PUT
// /untagged/anon).
func NewUntaggedAnonPutCommand(exec oascmd.ExecOptions) *cobra.Command {
	cmd := &cobra.Command{
		Use:   "put",
		Short: "No operationId, no tags",
	}
	cmd.Flags().Bool("json", false, "print the raw JSON response")
	cmd.RunE = func(cmd *cobra.Command, args []string) error {
		req := oascmd.Request{
			Method: "PUT",
			Path:   "/untagged/anon",
		}
		e := exec
		raw, _ := cmd.Flags().GetBool("json")
		e.Raw = e.Raw || raw
		if e.Out == nil {
			e.Out = os.Stdout
		}
		return oascmd.Execute(cmd.Context(), e, req)
	}
	return cmd
}
